version: "3.8"
services:
  vinf_recipes:
    build:
      context: "./"
    # ports:
    #   - "50070:50070"
    #   - "8088:8088"
    #   - "8080:8080"
    #   - "8042:8042"
    #   - "8081:8081"
    #   - "19888:19888"
    #we need these lines so container does not stop
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # command: sh -c "echo "cau""
    # command: >
    #   bash -c "echo 'Starting spark container'
    #   && hadoop fs -put /vinf_recipes/1
    #   && tail -f /dev/null"
    volumes:
      - ./:/vinf_recipes/
    #restart: always